### ISSUE TITLE
Pls give detailed description like what this do

### ISSUE THREAD

**Issue by reyyan987** [thebigcrafter/AdvancedPluginManager#6]
^^^^

**Comment by NhanAZ** [comment]
+1

**Comment by MintoD** [comment]
AdvancedPluginManager is an APT (AdvancedPackageTool)-like plugin manager on Linux. It downloads the plugin from the repo just like apt downloads the package from the repo. In short, AdvancedPluginManager (APM) is almost like Advanced Packaging Tool (APT) except that it downloads the plugin from the repository instead of the package that APT has been doing.
